= Otro post

:published_at: YYYY-mm-dd
:hp-tags: Tags, tag2, tag3

== Titulo 1
=== Titulo 2


http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#admon-bl

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#admon-bl[Asciidoc]

Contenido

Reference code like `types` or methods inline.

 Hola


|===
|Shortcut |Purpose

|kbd:[F11]
|Toggle fullscreen

|kbd:[Ctrl+T]
|Open a new tab

|kbd:[Ctrl+Shift+N]
|New incognito window

|kbd:[Ctrl + +]
|Increase zoom
|===

[[app-listing]]
[source,ruby]
.app.rb
----
require 'sinatra'

get '/hi' do <1>
  "Hello World!"
end
----


NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...

[quote, Abraham Lincoln, Address delivered at the dedication of the Cemetery at Gettysburg]
____
Four score and seven years ago our fathers brought forth
on this continent a new nation...
____

[quote, Albert Einstein]
A person who never made a mistake never tried anything new.

____
A person who never made a mistake never tried anything new.
____

[quote, Charles Lutwidge Dodgson, 'Mathematician and author, also known as http://en.wikipedia.org/wiki/Lewis_Carroll[Lewis Carroll]']
____
If you don't know where you are going, any road will get you there.
____

++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this embedded Gist:
</p>

<script src="http://gist.github.com/mojavelinux/5333524.js">
</script>++++






